catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from catalog.views import (
    ContactsTemplateView,
    HomeListView,
    ProductDetailView,
    ProductDeleteView,
    ProductCreateView,
    ProductUpdateView,
)

app_name = CatalogConfig.name

urlpatterns = [
    path("", HomeListView.as_view(), name="home"),
    path("contacts/", ContactsTemplateView.as_view(), name="contacts"),
    path("catalog/<int:pk>/", ProductDetailView.as_view(), name="product_view"),
    path("delete/<int:pk>/", ProductDeleteView.as_view(), name="delete"),
    path("create/", ProductCreateView.as_view(), name="create"),
    path("update/<int:pk>/", ProductUpdateView.as_view(), name="update"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', 'catalog')),
    path('bloging/', include('bloging.urls', 'bloging')),
    path('users/', include('users.urls', 'users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, email_verification, ProfileView, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("reset_password/", reset_password, name="reset_password"),
]

catalog/models.py
from email.policy import default

from django.db import models
from django.utils import timezone
from users.models import User

NULLABLE = {"null": True, "blank": True}


class Category(models.Model):
    name = models.CharField(max_length=250, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание", **NULLABLE)

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=250, verbose_name="Наименование")
    description = models.TextField(verbose_name="Описание", **NULLABLE)
    image = models.ImageField(upload_to="catalog/", verbose_name="Изображение", **NULLABLE)
    price = models.FloatField(verbose_name="Цена")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Дата создания")
    update_at = models.DateTimeField(default=timezone.now, verbose_name="Дата последнего изменения")
    user = models.ForeignKey(User, on_delete=models.SET_NULL, verbose_name="Создан пользователем", **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name="Признак публикации")

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        permissions = [
            ("set_published_status", )
        ]

    def __str__(self):
        return f'{self.name}{self.price}'


class Version(models.Model):
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, verbose_name='Продукт', related_name='version')
    number_version = models.IntegerField(default=1, verbose_name='Номер версии')
    name_version = models.CharField(max_length=250, verbose_name='Имя версии')
    version_flag = models.BooleanField(default=False, verbose_name='Признак версии')

    class Meta:
        verbose_name = 'Весрия'
        verbose_name_plural = 'Версии'

    def __str__(self):
        return f'{self.name_version}'

catalog/forms.py
from django import forms

from catalog.models import Product, Version
from common.views import StyleFormMixin


class ProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ("name", "description", "image", "price", "category")

    def clean_name(self):
        cleaned_data = self.cleaned_data.get("name")
        words = [
            "казино",
            "криптовалюта",
            "биржа",
            "дешево",
            "бесплатно",
            "обман",
            "полиция",
            "радар",
        ]
        for word in words:
            if word in cleaned_data:
                raise forms.ValidationError("Это запрещено здесЯ")
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get("description")
        words = [
            "казино",
            "криптовалюта",
            "биржа",
            "дешево",
            "бесплатно",
            "обман",
            "полиция",
            "радар",
        ]
        for word in words:
            if word in cleaned_data:
                raise forms.ValidationError("Это запрещено здесЯ")
        return cleaned_data


class ModeratorProductForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Product
        fields = ("category", "description", "is_published")


class VersionForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Version
        fields = ("number_version", "name_version", "version_flag")

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    DeleteView,
    UpdateView,
)

from catalog.forms import ProductForm, VersionForm, ModeratorProductForm
from catalog.models import Product, Version


# Create your views here.
class HomeListView(ListView):
    model = Product


class ContactsTemplateView(TemplateView):
    template_name = "catalog/contacts.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Контакты"
        return context

    def post(self, request, *args, **kwargs):
        name = request.POST.get("name")
        phone = request.POST.get("phone")
        message = request.POST.get("message")
        print(f'Имя: {name} \nТелефон: {phone} \nСообщение: {message}')
        return HttpResponseRedirect(reverse("catalog:contacts"))


class ProductDetailView(DetailView):
    model = Product


# def product(request, pk):
#     context = {'catalog': get_object_or_404(Product, pk=pk)}
#     return render(request, 'catalog/product_detail.html', context)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == "POST":
            context_data["formset"] = VersionFormset(self.request.POST)
        else:
            context_data["formset"] = VersionFormset()
        return context_data

    def form_valid(self, form):
        if form.is_valid:
            new_object = form.save(commit=False)
            new_object.user = self.request.user
            new_object.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:home")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == "POST":
            context_data["formset"] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data["formset"] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data["formset"]
        if form.is_valid() and formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form, formset=formset))


    def get_form_class(self):
        user = self.request.user
        if user == self.object.user or user.is_superuser:
            return ProductForm
        if (
            user.has_perm("catalog.set_published_status")
            and user.has_perm("catalog.change_description")
            and user.has_perm("catalog.change_category")
        ):
            return ModeratorProductForm
        raise PermissionDenied


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:home")

catalog/templates/catalog/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Напитки</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/include/inc_main_menu.html'%}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Напитки</h1>
    <p class="lead">Напитки - то место где вы можете попробовать, то что давно хотели</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Напитки
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
{% load static %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                           <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>8-800-555-35-35</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Старый Оскол, промзона Котел</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Текст сообщения" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}ь

catalog/templates/catalog/dase.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Напитки</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_main_menu.html'%}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Напитки</h1>
    <p class="lead">Напитки - то место где вы можете попробовать, то что давно хотели</p>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                Напитки
                <small class="d-block mb-3 text-muted">&copy; 2024</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
    <div class="row text-center">
        {% for product in product_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <img class="card-img-top" src="{{ product.image | media_filter }}">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ product.description|slice:100 }}</li>
                    </ul>
                     <h4 class="card-title pricing-card-title">{{ product.price }} руб.</h4>
                    <a href="{% url 'catalog:product' product.pk %}" type="button" class="btn btn-lg btn-block btn-outline-primary">Подробнее</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product.html
<!doctype html>
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ catalog.name }}</h4>
                </div>
                <div class="card-body">
                    <img class="card-img-top" src="{{ catalog.image | media_filter }}">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ catalog.description }}</li>
                        <li>Категория - {{ catalog.category }}</li>
                        <li> создана позиция - {{ catalog.created_at }}</li>
                        <li> Последнее изм. поз. - {{ catalog.update_at }}</li>
                    </ul>
                    <h4 class="card-title pricing-card-title">{{ catalog.price }} руб.</h4>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="container px-3 py-3 pt-md-5 pb-md-4">
<div class="col-12 mb-5 pt-md-5">
    <div class="row">
        <div class="col-lg-6 text-center">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить отзыв "{{ object.title }}"?</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'catalog:home' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
<!doctype html>
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
    <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                </div>
                <div class="card-body">
                    <img class="card-img-top" src="{{ object.image | media_filter }}">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.description }}</li>
                    </ul>
                    <h4 class="card-title pricing-card-title">{{ object.price }} руб.</h4>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                     <p class="lead">Владелец: {{ object.user.email }} </p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="col-12 mt-5">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6 text-center mt-5">
            <div class="card">
                <div class="card-header">
                    <div class="cart-title">
                        <h3>Продукт</h3>
                    </div>
                </div>
                <div class="card-body">

                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success btn-lg">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif %}
                    </button>

                </div>

            </div>
        </div>
        <div class="col-6 text-center mt-5">
            <div class="card">
                <div class="card-header">
                    <div class="cart-title">
                        <h3>Оптимальная версия</h3>
                    </div>
                </div>
                <div class="card-body">
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                </div>

            </div>
        </div>

    </form>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
<!doctype html>
{% extends 'catalog/base.html' %}
{% block content %}
{% load my_tags %}
    {% if user.is_authenticated %}
    <a href="{% url 'catalog:create' %}" type="button" class="btn btn-lg btn-block mb-5 btn-outline-primary">Добавить Продукт</a>
    {% endif %}
    <div class="row text-center">
        {% for product in product_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ product.name }}</h4>
                </div>
                <div class="card-body">
                    <img class="card-img-top" src="{{ product.image | media_filter }}">
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ product.description|slice:100 }}</li>
                    </ul>
                    <h4 class="card-title pricing-card-title">{{ product.price }} руб.</h4>
                    <a href="{% url 'catalog:product_view' product.pk %}" type="button" class="btn btn-lg btn-block mb-1 btn-outline-primary">Подробнее</a>
                    {% if user == product.user or perms.catalog.set_published_status and perms.catalog.change_description and perms.catalog.change_category or user.is_superuser %}
                    <a href="{% url 'catalog:update' product.pk %}" type="button" class="btn btn-lg btn-block mb-1 btn-outline-warning">Редактировать</a>
                    <a href="{% url 'catalog:delete' product.pk %}" type="button" class="btn btn-lg btn-block btn-outline-danger">Удалить</a>
                    {% endif %}
                    {% for status in product.version.all %}
                    <p> Активная версия:<strong> {{ status.name_version }} </strong> </p>
                    <p> Номер версии:<strong> {{ status.number_version }} </strong> </p>
                    {% endfor %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}